### ISSUE TITLE
How to use cuQuantum as a backend

### ISSUE THREAD

**Issue by nadbp** [tensorly/quantum#7]
Hi,

Thank you for your great work! May I know how to use cuQuantum as a backend as mentioned in your paper? Could you please provide a code example?  How does the cuQuantum backend support autograd? Thank you very much!

**Comment by taylorpatti** [comment]
Hi nadbp.

There's currently no official support for cuQuantum with TensorLy-Quantum. Definitely feel free to request it on the NVIDIA website (e.g., I like TensorLy-Quantum and I'd like to see it supported). Also, if you'd like to discuss about NVIDIA/cuQuantum supported products for quantum simulation, feel free to email me at tpatti@nvidia.com and I'd be happy to chat.
